// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgRf_LggqtplwOQvs6xEa1bhjdTgec7Gg',
    appId: '1:1021529125725:web:19429e2a85d4da52982eb4',
    messagingSenderId: '1021529125725',
    projectId: 'sato-meow',
    authDomain: 'sato-meow.firebaseapp.com',
    storageBucket: 'sato-meow.firebasestorage.app',
    measurementId: 'G-7QK6J6EQL1',
    
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWeOnut0wSJJXeoWmsCvtSrH4DFykTNM',
    appId: '1:1021529125725:android:42b6fa519e2c6c41982eb4',
    messagingSenderId: '1021529125725',
    projectId: 'sato-meow',
    storageBucket: 'sato-meow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfEGJyhle4jGYvmR_51S_qGNEE3l6_M40',
    appId: '1:1021529125725:ios:8a1fcdca448278bf982eb4',
    messagingSenderId: '1021529125725',
    projectId: 'sato-meow',
    storageBucket: 'sato-meow.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfEGJyhle4jGYvmR_51S_qGNEE3l6_M40',
    appId: '1:1021529125725:ios:8a1fcdca448278bf982eb4',
    messagingSenderId: '1021529125725',
    projectId: 'sato-meow',
    storageBucket: 'sato-meow.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgRf_LggqtplwOQvs6xEa1bhjdTgec7Gg',
    appId: '1:1021529125725:web:413fd7b6159a1ba2982eb4',
    messagingSenderId: '1021529125725',
    projectId: 'sato-meow',
    authDomain: 'sato-meow.firebaseapp.com',
    storageBucket: 'sato-meow.firebasestorage.app',
    measurementId: 'G-5PZD3PLF8N',
  );

}